export const INGREDIENTS_ALL_REQUEST = 'INGREDIENTS_ALL_REQUEST'
export const INGREDIENTS_ALL_SUCCESS = 'INGREDIENTS_ALL_SUCCESS'
export const INGREDIENTS_ALL_FAIL = 'INGREDIENTS_ALL_FAIL'
export const SET_INGRIDIENT_TAB = 'SET_INGRIDIENT_TAB'

export const CHANGE_INGREDIENTS = 'CHANGE_INGREDIENTS'

export const ORDER_CLOSE = 'ORDER_CLOSE'
export const ORDER_FAIL = 'ORDER_FAIL'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_REQUEST = 'ORDER_REQUEST'

export const OPEN_INGREDIENT_DETAILS = 'OPEN_INGREDIENT_DETAILS'
export const CLOSE_INGREDIENT_DETAILS = 'CLOSE_INGREDIENT_DETAILS'
