export const INGREDIENTS_ALL_REQUEST = 'INGREDIENTS_ALL_REQUEST'
export const INGREDIENTS_ALL_SUCCESS = 'INGREDIENTS_ALL_SUCCESS'
export const INGREDIENTS_ALL_FAIL = 'INGREDIENTS_ALL_FAIL'
export const SET_INGRIDIENT_TAB = 'SET_INGRIDIENT_TAB'

export const CHANGE_INGREDIENTS = 'CHANGE_INGREDIENTS'
