export const INGREDIENTS_ALL_REQUEST: 'INGREDIENTS_ALL_REQUEST' = 'INGREDIENTS_ALL_REQUEST'
export const INGREDIENTS_ALL_SUCCESS: 'INGREDIENTS_ALL_SUCCESS' = 'INGREDIENTS_ALL_SUCCESS'
export const INGREDIENTS_ALL_FAIL: 'INGREDIENTS_ALL_FAIL' = 'INGREDIENTS_ALL_FAIL'
export const SET_INGRIDIENT_TAB: 'SET_INGRIDIENT_TAB' = 'SET_INGRIDIENT_TAB'

export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT'
export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT'
export const UPDATE_INGREDIENTS: 'UPDATE_INGREDIENTS' = 'UPDATE_INGREDIENTS'
export const RESET_INGREDIENTS: 'RESET_INGREDIENTS' = 'RESET_INGREDIENTS'

export const ORDER_CLOSE: 'ORDER_CLOSE' = 'ORDER_CLOSE'
export const ORDER_FAIL: 'ORDER_FAIL' = 'ORDER_FAIL'
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS'
export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST'

export const OPEN_ORDER_DETAILS: 'OPEN_ORDER_DETAILS' = 'OPEN_ORDER_DETAILS'
export const OPEN_INGREDIENT_DETAILS: 'OPEN_INGREDIENT_DETAILS' = 'OPEN_INGREDIENT_DETAILS'
export const CLOSE_INGREDIENT_DETAILS: 'CLOSE_INGREDIENT_DETAILS' = 'CLOSE_INGREDIENT_DETAILS'

export const LOGIN: 'LOGIN' = 'LOGIN'
export const LOGOUT: 'LOGOUT' = 'LOGOUT'
export const SET_USER_DATA: 'SET_USER_DATA' = 'SET_USER_DATA'
export const RESET_PASSWORD_START: 'RESET_PASSWORD_START' = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_END: 'RESET_PASSWORD_END' = 'RESET_PASSWORD_END'
