export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_CONNECTION_STOP: 'WS_CONNECTION_STOP' = 'WS_CONNECTION_STOP';

export const WS_AUTH_CONNECTION_START: 'WS_AUTH_CONNECTION_START' = 'WS_AUTH_CONNECTION_START';
export const WS_AUTH_CONNECTION_SUCCESS: 'WS_AUTH_CONNECTION_SUCCESS' = 'WS_AUTH_CONNECTION_SUCCESS';
export const WS_AUTH_CONNECTION_ERROR: 'WS_AUTH_CONNECTION_ERROR' = 'WS_AUTH_CONNECTION_ERROR';
export const WS_AUTH_CONNECTION_CLOSED: 'WS_AUTH_CONNECTION_CLOSED' = 'WS_AUTH_CONNECTION_CLOSED';
export const WS_AUTH_GET_MESSAGE: 'WS_AUTH_GET_MESSAGE' = 'WS_AUTH_GET_MESSAGE';
export const WS_AUTH_CONNECTION_STOP: 'WS_AUTH_CONNECTION_STOP' = 'WS_AUTH_CONNECTION_STOP';

export const wsActions = {
  wsStart: WS_CONNECTION_START,
  wsSuccess: WS_CONNECTION_SUCCESS,
  wsError: WS_CONNECTION_ERROR,
  wsClosed: WS_CONNECTION_CLOSED,
  wsMessage: WS_GET_MESSAGE,
  wsStop: WS_CONNECTION_STOP
};

export const wsAuthActions = {
  wsStart: WS_AUTH_CONNECTION_START,
  wsSuccess: WS_AUTH_CONNECTION_SUCCESS,
  wsError: WS_AUTH_CONNECTION_ERROR,
  wsClosed: WS_AUTH_CONNECTION_CLOSED,
  wsMessage: WS_AUTH_GET_MESSAGE,
  wsStop: WS_AUTH_CONNECTION_STOP
};
